/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
#include "resource_statistics.h"

#include <map>
#include <string>

#include "common/log_inner.h"

namespace {
    const std::map<acl::ResourceType, std::string> RESOURCE_TPYR_TO_STRING = {
        {acl::ACL_STATISTICS_MALLOC_FREE, "ACL_STATISTICS_MALLOC_FREE"},
        {acl::ACL_STATISTICS_MALLOC_FREE_HOST, "ACL_STATISTICS_MALLOC_FREE_HOST"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_CONTEXT, "ACL_STATISTICS_CREATE_DESTROY_CONTEXT"},
        {acl::ACL_STATISTICS_SET_RESET_DEVICE, "ACL_STATISTICS_SET_RESET_DEVICE"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_EVENT, "ACL_STATISTICS_CREATE_DESTROY_EVENT"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_STREAM, "ACL_STATISTICS_CREATE_DESTROY_STREAM"},
        {acl::ACL_STATISTICS_DVPP_MALLOC_FREE, "ACL_STATISTICS_DVPP_MALLOC_FREE"},
        {acl::ACL_STATISTICS_RECORD_RESET_EVENT, "ACL_STATISTICS_RECORD_RESET_EVENT"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DATA_BUFFER, "ACL_STATISTICS_CREATE_DESTROY_DATA_BUFFER"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_TENSOR_DESC, "ACL_STATISTICS_CREATE_DESTROY_TENSOR_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DESC, "ACL_STATISTICS_CREATE_DESTROY_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DATASET, "ACL_STATISTICS_CREATE_DESTROY_DATASET"},
        {acl::ACL_STATISTICS_CREATE_LOAD_UNLOAD_MODEL, "ACL_STATISTICS_CREATE_LOAD_UNLOAD_MODEL"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_AIPP, "ACL_STATISTICS_CREATE_DESTROY_AIPP"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_ATTR, "ACL_STATISTICS_CREATE_DESTROY_ATTR"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_HANDLE, "ACL_STATISTICS_CREATE_DESTROY_HANDLE"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_CHANNEL_DESC, "ACL_STATISTICS_CREATE_DESTROY_DVPP_CHANNEL_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_PIC_DESC, "ACL_STATISTICS_CREATE_DESTROY_DVPP_PIC_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_ROI_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_DVPP_ROI_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_RESIZE_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_DVPP_RESIZE_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_JPEGE_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_DVPP_JPEGE_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VDEC_CHANNEL_DESC, "ACL_STATISTICS_CREATE_DESTROY_VDEC_CHANNEL_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VENC_CHANNEL_DESC, "ACL_STATISTICS_CREATE_DESTROY_VENC_CHANNEL_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_STREAM_DESC, "ACL_STATISTICS_CREATE_DESTROY_DVPP_STREAM_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VDEC_FRAME_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_VDEC_FRAME_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VENC_FRAME_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_VENC_FRAME_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_CHANNEL, "ACL_STATISTICS_CREATE_DESTROY_DVPP_CHANNEL"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VDEC_CHANNEL, "ACL_STATISTICS_CREATE_DESTROY_VDEC_CHANNEL"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_VENC_CHANNEL, "ACL_STATISTICS_CREATE_DESTROY_VENC_CHANNEL"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_DVPP_BATCH_PIC_DESC, "ACL_STATISTICS_CREATE_DESTROY_DVPP_BATCH_PIC_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_GROUP_INFO, "ACL_STATISTICS_CREATE_DESTROY_GROUP_INFO"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_PROF_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_PROF_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_PROF_SUB_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_PROF_SUB_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_MODEL_CONFIG, "ACL_STATISTICS_CREATE_DESTROY_MODEL_CONFIG"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_QUEUE_ID, "ACL_STATISTICS_CREATE_DESTROY_QUEUE_ID"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_QUEUE_ATTR, "ACL_STATISTICS_CREATE_DESTROY_QUEUE_ATTR"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE, "ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE_LIST, "ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE_LIST"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE_QUERY, "ACL_STATISTICS_CREATE_DESTROY_QUEUE_ROUTE_QUERY"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_MBUF, "ACL_STATISTICS_CREATE_DESTROY_MBUF"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_GRAPH_DUMP_OPTION, "ACL_STATISTICS_CREATE_DESTROY_GRAPH_DUMP_OPTION"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_ALLOCATOR_DESC, "ACL_STATISTICS_CREATE_DESTROY_ALLOCATOR_DESC"},
        {acl::ACL_STATISTICS_CREATE_DESTROY_ALLOCATOR_BINARY_DESC, "ACL_STATISTICS_CREATE_DESTROY_ALLOCATOR_BINARY_DESC"},
        {acl::ACL_STATISTICS_RESERVE_RELEASE_MEMORY_ADDRESS, "ACL_STATISTICS_RESERVE_RELEASE_MEMORY_ADDRESS"},
        {acl::ACL_STATISTICS_MALLOC_FREE_PHYSICAL_MEMORY, "ACL_STATISTICS_MALLOC_FREE_PHYSICAL_MEMORY"},
        {acl::ACL_STATISTICS_MAP_UNMAP_MEMORY, "ACL_STATISTICS_MAP_UNMAP_MEMORY"},
        {acl::ACL_STATISTICS_LOAD_UNLOAD_BINARY, "ACL_STATISTICS_LOAD_UNLOAD_BINARY"},
    };
}

namespace acl {
ResourceStatistics &ResourceStatistics::GetInstance()
{
    static ResourceStatistics theResourceStatistics;
    return theResourceStatistics;
}

void ResourceStatistics::AddApplyTotalCount(const ResourceType theResourceType)
{
    ++counter_[theResourceType].appplyReleaseValue[APPLY_TOTAL];
}

void ResourceStatistics::AddApplySuccCount(const ResourceType theResourceType)
{
    ++counter_[theResourceType].appplyReleaseValue[APPLY_SUCCESS];
}

void ResourceStatistics::AddReleaseTotalCount(const ResourceType theResourceType)
{
    ++counter_[theResourceType].appplyReleaseValue[RELEASE_TOTAL];
}

void ResourceStatistics::AddReleaseSuccCount(const ResourceType theResourceType)
{
    ++counter_[theResourceType].appplyReleaseValue[RELEASE_SUCCESS];
}

void ResourceStatistics::TraverseStatistics() const
{
    for (uint32_t i = 0U; i < ACL_STATISTICS_RESOURCE_TYPE_SIZE; ++i) {
        std::string resourceTypeToString;
        const auto iter = RESOURCE_TPYR_TO_STRING.find(static_cast<ResourceType>(i));
        if (iter == RESOURCE_TPYR_TO_STRING.end()) {
            ACL_LOG_DEBUG("The ResourceType:%u does not exist!", i);
            continue;
        } else {
            resourceTypeToString = iter->second;
        }

        ACL_LOG_EVENT("The ResourceType:%s, applyTotal = %lu, applySucc = %lu, releaseTotal = %lu, releaseSucc = %lu",
            resourceTypeToString.c_str(),
            counter_[i].appplyReleaseValue[APPLY_TOTAL].load(std::memory_order_relaxed),
            counter_[i].appplyReleaseValue[APPLY_SUCCESS].load(std::memory_order_relaxed),
            counter_[i].appplyReleaseValue[RELEASE_TOTAL].load(std::memory_order_relaxed),
            counter_[i].appplyReleaseValue[RELEASE_SUCCESS].load(std::memory_order_relaxed));
    }
}
}
