/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef ANALYSIS_DVVP_JOB_WRAPPER_PROF_INSTR_PERF_JOB_H
#define ANALYSIS_DVVP_JOB_WRAPPER_PROF_INSTR_PERF_JOB_H

#include "prof_comm_job.h"

namespace Analysis {
namespace Dvvp {
namespace JobWrapper {
using namespace analysis::dvvp::common::config;

class ProfInstrPerfJob : public ProfDrvJob {
public:
    ProfInstrPerfJob();
    ~ProfInstrPerfJob() override;
    int32_t Init(const SHARED_PTR_ALIA<CollectionJobCfg> cfg) override;
    int32_t Process() override;
    int32_t Uninit() override;

protected:
    uint32_t sampleCycle_{0};
    std::vector<uint32_t> groupIds_;
    AI_DRV_CHANNEL groupChannelIdMap_[INSTR_PROFILING_GROUP_MAX_NUM][INSTR_PROFILING_GROUP_CHANNEL_NUM] = {
        {PROF_CHANNEL_BIU_GROUP0_AIC, PROF_CHANNEL_BIU_GROUP0_AIV0, PROF_CHANNEL_BIU_GROUP0_AIV1},
        {PROF_CHANNEL_BIU_GROUP1_AIC, PROF_CHANNEL_BIU_GROUP1_AIV0, PROF_CHANNEL_BIU_GROUP1_AIV1},
        {PROF_CHANNEL_BIU_GROUP2_AIC, PROF_CHANNEL_BIU_GROUP2_AIV0, PROF_CHANNEL_BIU_GROUP2_AIV1},
        {PROF_CHANNEL_BIU_GROUP3_AIC, PROF_CHANNEL_BIU_GROUP3_AIV0, PROF_CHANNEL_BIU_GROUP3_AIV1},
        {PROF_CHANNEL_BIU_GROUP4_AIC, PROF_CHANNEL_BIU_GROUP4_AIV0, PROF_CHANNEL_BIU_GROUP4_AIV1},
        {PROF_CHANNEL_BIU_GROUP5_AIC, PROF_CHANNEL_BIU_GROUP5_AIV0, PROF_CHANNEL_BIU_GROUP5_AIV1},
        {PROF_CHANNEL_BIU_GROUP6_AIC, PROF_CHANNEL_BIU_GROUP6_AIV0, PROF_CHANNEL_BIU_GROUP6_AIV1},
        {PROF_CHANNEL_BIU_GROUP7_AIC, PROF_CHANNEL_BIU_GROUP7_AIV0, PROF_CHANNEL_BIU_GROUP7_AIV1},
        {PROF_CHANNEL_BIU_GROUP8_AIC, PROF_CHANNEL_BIU_GROUP8_AIV0, PROF_CHANNEL_BIU_GROUP8_AIV1},
        {PROF_CHANNEL_BIU_GROUP9_AIC, PROF_CHANNEL_BIU_GROUP9_AIV0, PROF_CHANNEL_BIU_GROUP9_AIV1},
        {PROF_CHANNEL_BIU_GROUP10_AIC, PROF_CHANNEL_BIU_GROUP10_AIV0, PROF_CHANNEL_BIU_GROUP10_AIV1},
        {PROF_CHANNEL_BIU_GROUP11_AIC, PROF_CHANNEL_BIU_GROUP11_AIV0, PROF_CHANNEL_BIU_GROUP11_AIV1},
        {PROF_CHANNEL_BIU_GROUP12_AIC, PROF_CHANNEL_BIU_GROUP12_AIV0, PROF_CHANNEL_BIU_GROUP12_AIV1},
        {PROF_CHANNEL_BIU_GROUP13_AIC, PROF_CHANNEL_BIU_GROUP13_AIV0, PROF_CHANNEL_BIU_GROUP13_AIV1},
        {PROF_CHANNEL_BIU_GROUP14_AIC, PROF_CHANNEL_BIU_GROUP14_AIV0, PROF_CHANNEL_BIU_GROUP14_AIV1},
        {PROF_CHANNEL_BIU_GROUP15_AIC, PROF_CHANNEL_BIU_GROUP15_AIV0, PROF_CHANNEL_BIU_GROUP15_AIV1},
        {PROF_CHANNEL_BIU_GROUP16_AIC, PROF_CHANNEL_BIU_GROUP16_AIV0, PROF_CHANNEL_BIU_GROUP16_AIV1},
        {PROF_CHANNEL_BIU_GROUP17_AIC, PROF_CHANNEL_BIU_GROUP17_AIV0, PROF_CHANNEL_BIU_GROUP17_AIV1},
        {PROF_CHANNEL_BIU_GROUP18_AIC, PROF_CHANNEL_BIU_GROUP18_AIV0, PROF_CHANNEL_BIU_GROUP18_AIV1},
        {PROF_CHANNEL_BIU_GROUP19_AIC, PROF_CHANNEL_BIU_GROUP19_AIV0, PROF_CHANNEL_BIU_GROUP19_AIV1},
        {PROF_CHANNEL_BIU_GROUP20_AIC, PROF_CHANNEL_BIU_GROUP20_AIV0, PROF_CHANNEL_BIU_GROUP20_AIV1},
        {PROF_CHANNEL_BIU_GROUP21_AIC, PROF_CHANNEL_BIU_GROUP21_AIV0, PROF_CHANNEL_BIU_GROUP21_AIV1},
        {PROF_CHANNEL_BIU_GROUP22_AIC, PROF_CHANNEL_BIU_GROUP22_AIV0, PROF_CHANNEL_BIU_GROUP22_AIV1},
        {PROF_CHANNEL_BIU_GROUP23_AIC, PROF_CHANNEL_BIU_GROUP23_AIV0, PROF_CHANNEL_BIU_GROUP23_AIV1},
        {PROF_CHANNEL_BIU_GROUP24_AIC, PROF_CHANNEL_BIU_GROUP24_AIV0, PROF_CHANNEL_BIU_GROUP24_AIV1}
    };
};

}
}
}
#endif